services:
  - type: web
    name: ayanfehub-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: http://localhost:5173,https://ayanfehub-frontend.vercel.app
      - key: FLUTTERWAVE_PUBLIC_KEY
        sync: false
      - key: FLUTTERWAVE_SECRET_KEY
        sync: false
      - key: FLUTTERWAVE_ENCRYPTION_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
